apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 3000
  
#     matchLabels:
#       app: client
#   template:
#     metadata:
#       name: client-pods
#       labels:
#         app: client
#     spec:
#       containers:
#         - name: client
#           image: dekcode/todo-app:v4
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: client-service
# spec:
#   type: ClusterIP
#   selector:
#     app: client
#   ports:
#     - port: 80
#       targetPort: 80

#       replicas: 3
  