version: '3.8'
services:
  web:
    build:
      context: ./
    env_file: .env
    volumes:
      - .:/src
    command: sh -c "npm run lint:fix && npm run start"
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
networks:
  service_network:
    driver: "bridge"